### ISSUE TITLE
maintaining hubdown

### ISSUE THREAD

**Issue by zeke** [electron/governance#126]
Hello @electron/wg-website 👋 

I am the author and one of the maintainers of `hubdown`, a module for converting markdown into GitHub-style HTML. It's used by electron/electronjs.org, electron/i18n, and help.github.com.

While attempting to help release an update to `hubdown` so @DeerMichel can add a special new "Open in Fiddle" feature to the website, I noticed I no longer have admin access to the repo. This project is set up with `semantic-release` and semantic-pull-requests, so releases should happen automatically. However they're not, as the GitHub token living in Travis CI no longer has the needed GitHub permissions.

A few questions:

- Can I join the website working group?
- Can I have admin access to electron/hubdown?
- What npm user/org do we use to publish to npm these days? cc @MarshallOfSound as I know you worked on some kind of npm 2FA automation...

Thanks!

**Comment by MarshallOfSound** [comment]
I can answer two of these, the website WG doesn't appear to have docs on the joining process (that I can find) so I'll leave that question to them (cc @Kilian @ckerr etc.)

> Can I have admin access to electron/hubdown?

Per our permissions policy --> https://github.com/electron/governance/blob/master/policy/permissions.md#repository-administrators no one should really be granted admin to a specific repo without specific requirements.  I think though this ask comes the 2FA / publish token requirement in question 3 so I hope the answer to that solves this one too 😄 

> What npm user/org do we use to publish to npm these days?

We use `electron-cfa` to publish npm releases and `electron-bot` to do the github side of things, if we want to set that up for hubdown I'm more than happy to spend some time helping folks get that working.  For CFA to work the CI needs to be running on CircleCI, also happy to help get that working at some point 👍 

Pretty sure the solution here is to just set up CFA 😄

**Comment by zeke** [comment]
Thanks for chiming in @MarshallOfSound 👋 

> Pretty sure the solution here is to just set up CFA 😄

Sounds good to me. I've added `electron-cfa` as an owner of the npm package:

```
$ npm owner add electron-cfa hubdown
+ electron-cfa (hubdown)
```

Next step, Circle config?

**Comment by MarshallOfSound** [comment]
@zeke I've turned on CircleCI for the `hubdown` repository.

Next steps are to follow the CFA setup steps here --> https://github.com/electron/cfa#set-up.  I'll set up the environment variables on CI so that it works.  Just need a CircleCI config / setup the latest versions of semantic release.

See https://github.com/electron/asar/pull/171/files for an example PR of setting up CFA

**Comment by MarshallOfSound** [comment]
@zeke Worth noting that CFA will refuse to publish a package as well that doesn't have 2FA turned on as a requirement so that needs to be enabled for `hubdown` as well at the package-level 👍

**Comment by Kilian** [comment]
@zeke sorry for the slow reply. 

> *    Can I join the website working group?

You're more than welcome. Let me see if I can make that happen as chair

**Comment by zeke** [comment]
Great! Let me know what you need from me.

**Comment by Kilian** [comment]
I think all points in this ticket have been resolved, so I'm closing it!
