### ISSUE TITLE
write access for hubdown

### ISSUE THREAD

**Issue by DeerMichel** [electron/governance#127]
Hi there, i'm currently working on `e/hubdown` and it would be convenient to being able to push branches directly to the repo instead of forking it. Can i get write access for it? I think a main problem with this repo is that it isn't (officially) governed by anyone rn. Thank you :)

**Comment by malept** [comment]
Given #126, it seems like that repository falls under the Website WG.

**Comment by DeerMichel** [comment]
Given https://github.com/electron/governance/blob/master/wg-website/repos.md, it doesn't.

**Comment by malept** [comment]
Well, no one's added a PR to that effect.

**Comment by QuantumADK** [comment]
Adk fix it

**Comment by Kilian** [comment]
Hi, Website WG chair here. We agreed to add it to our list of repo's. Beyond that  don't know the procedure for giving/getting access, but I'm looking into that now :)

**Comment by DeerMichel** [comment]
Thank you for following up. Forking worked well for me, so direct write access is not needed anymore 😉.
