### ISSUE TITLE
[Proposal] Form an Initiative to conduct the process of joining the OpenJS foundation

### ISSUE THREAD

**Issue by nornagon** [electron/governance#145]
Those who claimed interest at the recent maintainer's summit:

@codebytere
@cruzerld 
@felixrieseberg 
@groundwater 
@jkleinsc 
@keeganwatkins
@nornagon
@bnb

This issue is to discuss what the charter and delegated responsibilities of this initiative would be, form the initial set of members, and to produce a proposal for the Admin WG to bless.

**Comment by Charles90900** [comment]
.github/CODEOWNERS
