### ISSUE TITLE
[Proposal] Form an API Working Group

### ISSUE THREAD

**Issue by nornagon** [electron/governance#146]
This issue is to discuss forming a Working Group that would be responsible for shepherding Electron's API surface. At the recent maintainer's summit, it was generally agreed that it should be an explicit **non-goal** of this group to have a member of the WG review every change to APIs. However, the group **should** be responsible for creating and maintaining the processes by which Electron's APIs are made consistent, stable and developer-friendly.

A non-exhaustive list of examples of discussions that would happen within this group:
- Deprecating & removing the `remote` module. What should it be replaced with? What's our deprecation pathway?
- Exposing additional IPC primitives, such as transferring file descriptors or Mojo handles.
- Broad API change initiatives like changing get/set to properties.

Those who claimed interest during the maintainer's summit:
@MarshallOfSound 
@codebytere 
@ckerr 
@groundwater 
@nornagon 
@itsananderson
@Kilian 
@loc
@zcbenz 
@cruzerld 
@miniak 
@jkleinsc

**Comment by sofianguy** [comment]
🎉 https://github.com/electron/governance/pull/170
