### ISSUE TITLE
migrating the hubdown module to a new home

### ISSUE THREAD

**Issue by zeke** [electron/governance#164]
Hi @electron/wg-website friends 👋 

I'd like to request that we move the `hubdown` project from the @electron org to the @docs org and start publishing it to npm using a GitHub-owned npm account.

I work on the Product Documentation team at GitHub, maintaining help.github.com and developer.github.com. We make extensive use of `hubdown` and have a vested interest in keeping it updated, bug-free, and performant.

There was recently an effort to automate the npm publishing process for this module using multi-factor auth and semantic-release (thanks @deermichel and @MarshallOfSound!). That worked for a time, but it seems to have stopped working again and I don't have much visibility into the cause. Two weeks ago I landed a PR https://github.com/electron/hubdown/pull/20 to address a bug in the current version of `hubdown`. This PR was reviewed and merged in short order but unfortunately a new release was not triggered.

Would y'all be open to migrating this module to a new home where it will get more regular attention? We promise to follow SemVer and keep Electron folks in the loop as the project is updated. ✋ 

cc @sarahs @juliangruber @wooorm

**Comment by MarshallOfSound** [comment]
> That worked for a time, but it seems to have stopped working again and I don't have much visibility into the cause. Two weeks ago I landed a PR electron/hubdown#20 to address a bug in the current version of hubdown.

I thought I explained how the system worked at the time, but when a PR is merged someone needs to be around to enter a 2 factor code for the publish and in this case you merged it late at night and no one was around.  I only saw the notification the next day iirc.  The system works, just in this case you need to make sure that someone is actually around with a 2FA token.

I'm not strongly opinionated either way on this but I would highlight that if part of the reason for this request is to make it "easier" by removing the 2FA step for publishing I'm slightly against it.  I strongly believe that all npm packages should have 2FA for publishing and just because it adds a small level of inconvenience we shouldn't throw that additional safety away.

**Comment by felixrieseberg** [comment]
This sounds like you’re offering more help and official support from
GitHub, which seems like a 🎁 to me.

I’m pro!

**Comment by zeke** [comment]
@MarshallOfSound thanks for chiming in. I should clarify that I am pro-2FA and that you did indeed explain [how the system works](https://github.com/electron/cfa#set-up), but my issue is that as an outside contributor I don't have visibility into whether a release failed because of a technical issue, or because nobody was around to respond to the 2FA ping in Slack.

What would be the best way to ensure that someone is around to press the button for future releases?

I've opened a followup PR that can be merged when folks are around and ready to respond to the 2FA request: https://github.com/electron/hubdown/pull/21

All that said, I don't feel strongly about where this module lives. I just want to be sure that GitHub's Docs team can effectively make improvements as needed.

**Comment by zeke** [comment]
Friendly bump. This is still pending: https://github.com/electron/hubdown/pull/21

**Comment by zeke** [comment]
Hey I just realized that `hubdown` is actually [no longer used by the Electron website](https://github.com/electron/electronjs.org/pull/2160), so I think it makes sense to find a new home for it. We actively use `hubdown` for help.github.com, and would be happy to maintain it in the @docs org.

Can y'all help make that happen?

**Comment by deermichel** [comment]
Hey there, I think `hubdown` is still used for the Electron docs (https://github.com/electron/i18n). Anyway, I haven't worked on this for a while and might not have a complete overview of the current project structure.

**Comment by rashd640** [comment]
> مرحباً يا (الإلكترون/wg-الموقع الشبكي👋
> 
> أود أن أطلب أن نحرك الـ...`hubdown`مشروع من مشروع مشروع من(أ)من org إلى(د)org و ابدأ في نشرها إلى npm باستخدام حساب npm مملوك لـ (جيتHub).
> 
> أعمل في فريق توثيق المنتجات في جيتهوب، والحفاظ على المساعدة، github.com والمطور. github.com. نحن نستفيد من`hubdown`ولهم مصلحة في الحفاظ عليه محدثة، وخالية من الحشرات، وأداء.
> 
> وقد بُذلت مؤخراً جهداً لتأليف عملية نشر في هذه الوحدة باستخدام التعادل المتعدد العوامل والإطلاق الدلاي (شكراً(دي رمشيل)و(مارس مارس//ف سوند)هذا عمل لفترة من الوقت، ولكن يبدو أنه توقف عن العمل مرة أخرى وليس لدي الكثير من الرؤية في القضية. قبل أسبوعين هبطت في غرفة شرطة[الإلكترون/هوابوت رقم 20](https://github.com/electron/hubdown/pull/20)لمعالجة حشرة في النسخة الحالية من`hubdown`وقد تم استعراض هذا الاستعراض ودمجه في إطار قصير، ولكن للأسف لم يتم إطلاق إطلاق جديد.
> 
> هل ستكون منفتحة على الهجرة هذه الوحدة إلى منزل جديد حيث ستحصل على المزيد من الاهتمام المنتظم؟ نعد بأن نتبع (سيمفر) وأن نبقي شعب (إلكتون) في الحلقة مع تحديث المشروع✋
> 
> (ج ج ج)(سارات) (ج) جوليانغروبر دونة
