### ISSUE TITLE
Cordova needs help

### ISSUE THREAD

**Issue by LifeIsStrange** [electron/governance#181]
I don't know where is the best place to ask electron executives but this repository seems like a good central place.

Apache Cordova is the electron of mobile.
It is a foundational technology that allows developers to write hybrid web apps and to share most of the code with electron and the web, thus having critically high public utility.

Cordova has currently zero paid developper and a lack of maintenance.
Cordova needs contributions to get android 10 support.

I believe Cordova and Electron projects share a common goal of pushing the open web forward.

Electron has quickly got a huge success on the desktop and I expect it's only a matter of a few years until cordova get really popular.
The Electron project has gotten many sponsors, especially Microsoft.

I'm asking for the electron project to sponsor cordova as a friend project, and for electron sponsors, especially Microsoft (which is involved in chromium too with Edge) to give help and funding to this foundational technology.

Details:
apache/cordova#163

**Comment by groundwater** [comment]
On one hand, this is off topic for the governance repo, but on the other hand I understand not knowing the best way to reach out. Generally info@electronjs.org is the best option for unsolicited/general inquiries. Given that, not every inquiry will get a response. 

I will admit openly this is unlikely to get a positive reply if any. Consider reaching out directly to affected companies, as Electron maintainers may not be the right point of contact.
