### ISSUE TITLE
Transfer official domains to OpenJS Foundation

### ISSUE THREAD

**Issue by bnb** [electron/governance#439]
I'm not sure if this needs to be done, if some decision was made to keep the status quo, or something else, but it's one of the remaining "open" tasks in https://github.com/electron/governance/issues/267.

**Comment by bnb** [comment]
(0pened at @MarshallOfSound's request)

**Comment by MarshallOfSound** [comment]
I can't remember where this settled @groundwater , we might just be able to close the books as "we convinced them to let us maintain the status quo" but I don't recall where these discussions ended

**Comment by Sami-ab** [comment]
001380001*

**Comment by codebytere** [comment]
Closing in light of the above and given multiple years of inactivity but of course feel free to re-open if there is further action to be considered.
