### ISSUE TITLE
Transfer logomark to the OpenJS Foundation

### ISSUE THREAD

**Issue by bnb** [electron/governance#440]
I'm not sure if this was completed or not, but it's one of the final things with #267.

**Comment by MarshallOfSound** [comment]
@groundwater Any idea where we stand with this?

**Comment by Sami-ab** [comment]
001380001*

**Comment by erickzhao** [comment]
pretty sure we've done this in some capacity https://github.com/openjs-foundation/artwork/tree/main/projects/electron
