### ISSUE TITLE
GitHub Org clean-up

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/governance#443]
This has been a long running action item to remove folks from the GitHub org that aren't actively part of governance.  There are a few reasons for this but it mostly comes down to:

* Security, being part of the org grants access to certain things that we want to keep scoped
* Communication, just being a member of the org gives you a "Member" badge and comments are inherently thought of as "official" whether they are part of governance or not
* Cost, with some features of GHE being limited to org members we don't want to give things like codespaces access to the large quantity of folks that are currently in the org

I'll collect a list of folks I intend to remove and tag them in this issue so they are aware of what is happening.

Folks with guest access to our Slack instance will retain that access, we have no plans to remove guests at this time.

**Comment by MarshallOfSound** [comment]
@50Wliu @aaronabramov @abelmathew @adill @AdrienFery @AGS- @ahirun0426 @aishamidori @ajmacd @akost @alespergl @alessandroliveri @alexeykuzmin @alexstrat @amclegg @amiechen @amorist @anri-asaturov @arifcakiroglu @ArisLittle @asheren @avidrissman @bandantonio @bbondy @bengotow @benogle @billygriffin @BinaryMuse @bitdisaster @blaatunga @bobbyb-arm @bpasero @brenca @brianamarie @bridiver @brntbeer @brycebaril @bsclifton @bureken @chadluo @CharlieHess @ChrisFan @chuckdoerr-zz @chungkikelly @CliftonH @cmwinters @comatory @concreted @danhp @danielbuechele

**Comment by MarshallOfSound** [comment]
@darkdh @dchest @dead-horse @deanihansen @demopark @deopard @diracdeltas @dongjoon-hyun @dooglio @dshaw @duncup @echjordan @ecmadao @edkogan @electron-bot @electron-triage @elfisher @emorikawa @enlight @evanw @everblut @excfergodst @fbukevin @feross @fierroformo @flohdot @fplucas @frankshaka @frantic @FranzDeCopenhague @gerges-zz @gerhardberger @gibfahn @gnahzak @Godoy @gsathya @guillaumeguerin @gvoropaev @HarsimranSingh @hashseed @HazAT @heapwolf @hectorsector @Hiroyuki-Anzai @hokein @holiman @hugomano @igorkofman @ikkisoft @imelven

**Comment by MarshallOfSound** [comment]
@imenkov @iolsen @issacgerges @izuzak @j5a @jakubzitny @jameseneal @jan-auer @jasonrudolph @javan @jaysturm @jhen0409 @jhgg @jlfwong @jlord @joaomoreno @joemccann @john-hern @johnhaley81 @joneian @jonycheung @josephfrazier @joshaber @jprichardson @juliangruber @juturu @jviotti @katelynbryant @katmeister @kaylie-alexa @kcrt @keithamus @kellyxvx @kevinsawicki @KiaFathi @Kthulu120 @kuychaco @kwonoj @kyokutyo @laiso @LaurentLeVan-zz @leereilly @leo @leroix @liliakai @liuderchi @LizzHale @loc @lockys @LukasReschke

**Comment by MarshallOfSound** [comment]
@mafintosh @magne4000 @maleeb @matheuss @matiasinsaurralde @maxbrunsfeld @maxfeldman14 @mayanksinghal @mczlr @mgc @mike-engel @MileAit @mitsuhiko @mkscrg @mnquintana @Mr0grog @mvoltairec @MylesBorins @nakajima @natebwangsut @nathos @nekolab @newsoft @Nirmal4G @nitsakh @nkolba @numaanashraf @odensc @omichelsen @othiym23 @outofambit @ovo4096 @petrbrzek @pfrazee @pierreneter @pifafu @pmarsceill @pmn @poiru @preco21 @queue-tea @radekdomin @Raul6469 @rdepena @reillyeon @renatoalencar @roramirez @rosa @runinspring @RyanZim

**Comment by MarshallOfSound** [comment]
@ryo-a @ryzokuken @sairoutine @samiskin @sbahra @scarvell @schwalbe10 @serant @sethlu @shiftkey @Shin-Ogata @shubham2892 @simonmysun @simurai @sitdh @smashwilson @sonnens @sophshep @sotayamashita @srajko @stephanwlee @t-hiroishi @takashi @tangollama @tarruda @tclem @TGWKE @TiagoDanin @timfish @tommoor @torycl @tsekityam @tvst-electron @Tyriar @V-E-O @vaenow @vanessayuenn @vladimirkononov @vreality64 @watilde @wbinnssmith @WenryXu @weolar @wgrafael @wiltord @x-yao @x87 @Yukaii @zhenchaoli @zkat

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @MarshallOfSound . I'm okay for the removal.

**Comment by matiasinsaurralde** [comment]
No worries

**Comment by bsclifton** [comment]
Thanks for the ping - definitely 👍 on removal 😄 Brave has migrated away from Electron / our fork a while back

**Comment by dooglio** [comment]
Yeah go ahead and remove me since I'm not an active contributor.

**Comment by shiftkey** [comment]
No objections from me @MarshallOfSound

**Comment by comatory** [comment]
Remove me as well thanks.

**Comment by Mr0grog** [comment]
Yep, I’m no longer an active contributor, 👍 on removing me!

**Comment by pfrazee** [comment]
:+1: to remove me, cheers

**Comment by iolsen** [comment]
This is a good idea. No complaints from me!

**Comment by MarshallOfSound** [comment]
Just to stop 250 people getting an email every time someone says 👍 I'm going to lock this, if you have specific questions please feel free to raise a new issue on this repository but keep in mind this change is just enacting our already existing policies

**Comment by MarshallOfSound** [comment]
This has been done, closing this out 👍
